// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sellora.CoreService.Infrastructure.Persistence;

#nullable disable

namespace Sellora.CoreService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20260825150449_InitialOrganizationSchema")]
    partial class InitialOrganizationSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.Agency", b =>
                {
                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("province_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("AgencyId")
                        .HasName("pk_agency");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProvinceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_agency_province_name");

                    b.ToTable("agency", null, t =>
                        {
                            t.HasCheckConstraint("ck_agency_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.AgencyOperatorAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("AssignmentId")
                        .HasName("pk_agency_operator_assignment");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_agency_operator_assignment_agency");

                    b.HasIndex("CompanyId");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("ix_agency_operator_assignment_operator");

                    b.ToTable("agency_operator_assignment", null, t =>
                        {
                            t.HasCheckConstraint("ck_agency_operator_assignment_dates", "ends_at IS NULL OR ends_at > starts_at");
                        });
                });

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TenantCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tenant_code");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CompanyId")
                        .HasName("pk_company");

                    b.HasIndex("TenantCode")
                        .IsUnique()
                        .HasDatabaseName("uq_company_tenant_code");

                    b.ToTable("company", null, t =>
                        {
                            t.HasCheckConstraint("ck_company_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("aggregate_type");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.HasKey("OutboxId")
                        .HasName("pk_outbox_message");

                    b.HasIndex("CompanyId");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.Province", b =>
                {
                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("province_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("ProvinceId")
                        .HasName("pk_province");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_province_company_code");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_province_company_name");

                    b.ToTable("province", null, t =>
                        {
                            t.HasCheckConstraint("ck_province_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.ProvinceManagerAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<Guid>("AreaManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_manager_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("province_id");

                    b.Property<Guid?>("ReportsToAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("reports_to_admin_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("AssignmentId")
                        .HasName("pk_province_manager_assignment");

                    b.HasIndex("AreaManagerId")
                        .HasDatabaseName("ix_province_manager_assignment_area_manager");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProvinceId")
                        .IsUnique()
                        .HasDatabaseName("uq_province_manager_assignment_active_province")
                        .HasFilter("\"ends_at\" IS NULL");

                    b.HasIndex("ReportsToAdminId");

                    b.ToTable("province_manager_assignment", null, t =>
                        {
                            t.HasCheckConstraint("ck_province_manager_assignment_dates", "ends_at IS NULL OR ends_at > starts_at");
                        });
                });

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.SalesRepTerritoryAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("SalesRepId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_rep_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<Guid>("TerritoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("territory_id");

                    b.HasKey("AssignmentId")
                        .HasName("pk_sales_rep_territory_assignment");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SalesRepId")
                        .IsUnique()
                        .HasDatabaseName("uq_sales_rep_assignment_active_rep")
                        .HasFilter("\"ends_at\" IS NULL");

                    b.HasIndex("TerritoryId")
                        .IsUnique()
                        .HasDatabaseName("uq_sales_rep_assignment_active_territory")
                        .HasFilter("\"ends_at\" IS NULL");

                    b.ToTable("sales_rep_territory_assignment", null, t =>
                        {
                            t.HasCheckConstraint("ck_sales_rep_territory_assignment_dates", "ends_at IS NULL OR ends_at > starts_at");
                        });
                });

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.Shop", b =>
                {
                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("credit_limit");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("owner_email");

                    b.Property<string>("OwnerIdentitySub")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("owner_identity_sub");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("owner_name");

                    b.Property<string>("OwnerPhone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("owner_phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TerritoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("territory_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ShopId")
                        .HasName("pk_shop");

                    b.HasIndex("CompanyId");

                    b.HasIndex("OwnerIdentitySub")
                        .IsUnique()
                        .HasDatabaseName("uq_shop_owner_identity_sub");

                    b.HasIndex("TerritoryId");

                    b.ToTable("shop", null, t =>
                        {
                            t.HasCheckConstraint("ck_shop_credit_limit", "credit_limit >= 0");

                            t.HasCheckConstraint("ck_shop_latitude", "latitude >= -90 AND latitude <= 90");

                            t.HasCheckConstraint("ck_shop_longitude", "longitude >= -180 AND longitude <= 180");

                            t.HasCheckConstraint("ck_shop_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.StaffProfile", b =>
                {
                    b.Property<Guid>("StaffProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_profile_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("IdentitySub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("identity_sub");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("StaffProfileId")
                        .HasName("pk_staff_profile");

                    b.HasIndex("CompanyId");

                    b.HasIndex("IdentitySub")
                        .IsUnique()
                        .HasDatabaseName("uq_staff_profile_identity_sub");

                    b.ToTable("staff_profile", null, t =>
                        {
                            t.HasCheckConstraint("ck_staff_profile_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.Territory", b =>
                {
                    b.Property<Guid>("TerritoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("territory_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GeographicDescription")
                        .HasColumnType("text")
                        .HasColumnName("geographic_description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("province_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("TerritoryId")
                        .HasName("pk_territory");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_territory_company_code");

                    b.HasIndex("ProvinceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_territory_province_name");

                    b.ToTable("territory", null, t =>
                        {
                            t.HasCheckConstraint("ck_territory_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.TerritoryAgencyAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<Guid>("TerritoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("territory_id");

                    b.HasKey("AssignmentId")
                        .HasName("pk_territory_agency_assignment");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_territory_agency_assignment_agency");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TerritoryId")
                        .IsUnique()
                        .HasDatabaseName("uq_territory_agency_assignment_active_territory")
                        .HasFilter("\"ends_at\" IS NULL");

                    b.ToTable("territory_agency_assignment", null, t =>
                        {
                            t.HasCheckConstraint("ck_territory_agency_assignment_dates", "ends_at IS NULL OR ends_at > starts_at");
                        });
                });

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.Agency", b =>
                {
                    b.HasOne("Sellora.CoreService.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agency_company");

                    b.HasOne("Sellora.CoreService.Domain.Entities.Province", null)
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agency_province");
                });

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.AgencyOperatorAssignment", b =>
                {
                    b.HasOne("Sellora.CoreService.Domain.Entities.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agency_operator_assignment_agency");

                    b.HasOne("Sellora.CoreService.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agency_operator_assignment_company");

                    b.HasOne("Sellora.CoreService.Domain.Entities.StaffProfile", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agency_operator_assignment_operator");
                });

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.OutboxMessage", b =>
                {
                    b.HasOne("Sellora.CoreService.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_outbox_message_company");
                });

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.Province", b =>
                {
                    b.HasOne("Sellora.CoreService.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_province_company");
                });

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.ProvinceManagerAssignment", b =>
                {
                    b.HasOne("Sellora.CoreService.Domain.Entities.StaffProfile", null)
                        .WithMany()
                        .HasForeignKey("AreaManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_province_manager_assignment_area_manager");

                    b.HasOne("Sellora.CoreService.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_province_manager_assignment_company");

                    b.HasOne("Sellora.CoreService.Domain.Entities.Province", null)
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_province_manager_assignment_province");

                    b.HasOne("Sellora.CoreService.Domain.Entities.StaffProfile", null)
                        .WithMany()
                        .HasForeignKey("ReportsToAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_province_manager_assignment_reports_to_admin");
                });

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.SalesRepTerritoryAssignment", b =>
                {
                    b.HasOne("Sellora.CoreService.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_rep_territory_assignment_company");

                    b.HasOne("Sellora.CoreService.Domain.Entities.StaffProfile", null)
                        .WithMany()
                        .HasForeignKey("SalesRepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_rep_territory_assignment_sales_rep");

                    b.HasOne("Sellora.CoreService.Domain.Entities.Territory", null)
                        .WithMany()
                        .HasForeignKey("TerritoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_rep_territory_assignment_territory");
                });

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.Shop", b =>
                {
                    b.HasOne("Sellora.CoreService.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shop_company");

                    b.HasOne("Sellora.CoreService.Domain.Entities.Territory", null)
                        .WithMany()
                        .HasForeignKey("TerritoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shop_territory");
                });

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.StaffProfile", b =>
                {
                    b.HasOne("Sellora.CoreService.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_profile_company");
                });

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.Territory", b =>
                {
                    b.HasOne("Sellora.CoreService.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_territory_company");

                    b.HasOne("Sellora.CoreService.Domain.Entities.Province", null)
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_territory_province");
                });

            modelBuilder.Entity("Sellora.CoreService.Domain.Entities.TerritoryAgencyAssignment", b =>
                {
                    b.HasOne("Sellora.CoreService.Domain.Entities.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_territory_agency_assignment_agency");

                    b.HasOne("Sellora.CoreService.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_territory_agency_assignment_company");

                    b.HasOne("Sellora.CoreService.Domain.Entities.Territory", null)
                        .WithMany()
                        .HasForeignKey("TerritoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_territory_agency_assignment_territory");
                });
#pragma warning restore 612, 618
        }
    }
}
